"""add_player_table

Revision ID: 86219af15bfd
Revises: 22a63f363efc
Create Date: 2025-08-09 11:02:39.687317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86219af15bfd'
down_revision: Union[str, Sequence[str], None] = '22a63f363efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create players table
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jersey_number')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    
    # Update player_game_stats table using batch mode for SQLite
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('player_game_stats_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('player_game_stats_player_id_fkey', 'players', ['player_id'], ['id'])
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert player_game_stats table changes using batch mode for SQLite
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('player_game_stats_player_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('player_game_stats_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('player_id')
    
    # Drop players table
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
